import { useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

export type ReportType = 'executive' | 'threat_analysis' | 'resilience' | 'analytics' | 'watchlist' | 'dss_assessment';

interface ReportData {
  title: string;
  executive_summary: string;
  key_findings: string[];
  detailed_analysis: string;
  recommendations: string[];
  risk_assessment: string;
  appendices?: string[];
  metadata: {
    generated_at: string;
    report_type: string;
    time_period: string;
    author: string;
  };
}

interface GenerateReportOptions {
  type: ReportType;
  title?: string;
  data?: any;
  time_period?: string;
  format?: 'markdown' | 'html' | 'json';
}

export const useAIReportGeneration = () => {
  const { user } = useAuth();
  const [isGenerating, setIsGenerating] = useState(false);
  const [lastGeneratedReport, setLastGeneratedReport] = useState<ReportData | null>(null);

  const generateReport = async (options: GenerateReportOptions): Promise<ReportData | null> => {
    if (!user) {
      toast.error('Please log in to generate reports');
      return null;
    }

    setIsGenerating(true);
    
    try {
      console.log(`Generating ${options.type} report...`);
      
      toast.info(`🤖 Generating ${options.type.replace('_', ' ')} report with AI...`, {
        duration: 3000
      });

      const { data, error } = await supabase.functions.invoke('ai-report-generation', {
        body: {
          type: options.type,
          user_id: user.id,
          title: options.title,
          data: options.data,
          time_period: options.time_period || 'current',
          format: options.format || 'json'
        }
      });

      if (error) throw error;

      if (data?.report) {
        setLastGeneratedReport(data.report);
        
        toast.success(`📄 ${data.report.title} generated successfully!`, {
          duration: 5000
        });

        return data.report;
      } else {
        throw new Error('No report data received');
      }

    } catch (error: any) {
      console.error('Report generation failed:', error);
      toast.error(`Failed to generate report: ${error.message}`);
      return null;
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadReport = (report: ReportData, format: 'txt' | 'json' | 'html' = 'txt') => {
    try {
      let content = '';
      let mimeType = 'text/plain';
      let extension = 'txt';

      switch (format) {
        case 'json':
          content = JSON.stringify(report, null, 2);
          mimeType = 'application/json';
          extension = 'json';
          break;
        case 'html':
          content = convertToHTML(report);
          mimeType = 'text/html';
          extension = 'html';
          break;
        default:
          content = convertToText(report);
          mimeType = 'text/plain';
          extension = 'txt';
      }

      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      
      const fileName = `${report.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.${extension}`;
      
      const link = document.createElement('a');
      link.href = url;
      link.download = fileName;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      URL.revokeObjectURL(url);
      
      toast.success(`📥 Report downloaded as ${fileName}`);
      
    } catch (error) {
      console.error('Download failed:', error);
      toast.error('Failed to download report');
    }
  };

  const shareReport = async (report: ReportData) => {
    try {
      if (navigator.share) {
        await navigator.share({
          title: report.title,
          text: report.executive_summary,
          url: window.location.href
        });
      } else {
        // Fallback: copy to clipboard
        const shareText = `${report.title}\n\n${report.executive_summary}\n\nGenerated by AI Intelligence System`;
        await navigator.clipboard.writeText(shareText);
        toast.success('📋 Report summary copied to clipboard');
      }
    } catch (error) {
      console.error('Share failed:', error);
      toast.error('Failed to share report');
    }
  };

  return {
    generateReport,
    downloadReport,
    shareReport,
    isGenerating,
    lastGeneratedReport
  };
};

// Helper functions for format conversion
function convertToText(report: ReportData): string {
  return `${report.title}
Generated: ${new Date(report.metadata.generated_at).toLocaleString()}
Report Type: ${report.metadata.report_type}
Time Period: ${report.metadata.time_period}

EXECUTIVE SUMMARY
${report.executive_summary}

KEY FINDINGS
${report.key_findings.map((finding, index) => `${index + 1}. ${finding}`).join('\n')}

DETAILED ANALYSIS
${report.detailed_analysis}

RECOMMENDATIONS
${report.recommendations.map((rec, index) => `${index + 1}. ${rec}`).join('\n')}

RISK ASSESSMENT
${report.risk_assessment}

${report.appendices && report.appendices.length > 0 ? `
APPENDICES
${report.appendices.map((appendix, index) => `${index + 1}. ${appendix}`).join('\n')}
` : ''}

---
Report generated by AI Intelligence System
${report.metadata.author} • ${report.metadata.generated_at}`;
}

function convertToHTML(report: ReportData): string {
  return `<!DOCTYPE html>
<html>
<head>
    <title>${report.title}</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; }
        h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
        h2 { color: #1e40af; margin-top: 30px; }
        .metadata { background: #f3f4f6; padding: 15px; border-radius: 8px; margin-bottom: 20px; }
        .finding { margin-bottom: 10px; }
        .recommendation { margin-bottom: 10px; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; }
    </style>
</head>
<body>
    <h1>${report.title}</h1>
    
    <div class="metadata">
        <strong>Generated:</strong> ${new Date(report.metadata.generated_at).toLocaleString()}<br>
        <strong>Report Type:</strong> ${report.metadata.report_type}<br>
        <strong>Time Period:</strong> ${report.metadata.time_period}
    </div>

    <h2>Executive Summary</h2>
    <p>${report.executive_summary}</p>

    <h2>Key Findings</h2>
    ${report.key_findings.map((finding, index) => 
        `<div class="finding">${index + 1}. ${finding}</div>`
    ).join('')}

    <h2>Detailed Analysis</h2>
    <p>${report.detailed_analysis.replace(/\n/g, '</p><p>')}</p>

    <h2>Recommendations</h2>
    ${report.recommendations.map((rec, index) => 
        `<div class="recommendation">${index + 1}. ${rec}</div>`
    ).join('')}

    <h2>Risk Assessment</h2>
    <p>${report.risk_assessment}</p>

    ${report.appendices && report.appendices.length > 0 ? `
    <h2>Appendices</h2>
    ${report.appendices.map((appendix, index) => 
        `<div>${index + 1}. ${appendix}</div>`
    ).join('')}
    ` : ''}

    <div class="footer">
        Report generated by AI Intelligence System<br>
        ${report.metadata.author} • ${report.metadata.generated_at}
    </div>
</body>
</html>`;
}