import { useToast } from "@/hooks/use-toast";

interface Report {
  id: string;
  title: string;
  category: string;
  severity: string;
  time_period: string;
  description?: string;
  created_at: string;
}

export const useReportDownload = () => {
  const { toast } = useToast();

  const generateReportPDF = (report: Report) => {
    // Generate report content
    const reportContent = generateReportText(report);
    
    // Create a blob with the report content
    const blob = new Blob([reportContent], { type: 'text/plain' });
    
    // Create download link
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${report.title.replace(/[^a-zA-Z0-9]/g, '_')}_${report.id.slice(0, 8)}.txt`;
    
    // Trigger download
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
    
    return true;
  };

  const generateReportText = (report: Report): string => {
    const currentDate = new Date().toLocaleDateString();
    
    return `
THREAT INTELLIGENCE REPORT
==========================

Title: ${report.title}
Category: ${report.category}
Severity: ${report.severity.toUpperCase()}
Time Period: ${report.time_period}
Generated: ${currentDate}
Report ID: ${report.id}

EXECUTIVE SUMMARY
=================

This ${report.severity.toLowerCase()} severity report covers ${report.category.toLowerCase()} threats observed during the ${report.time_period} period. The analysis identifies key risk factors and provides actionable intelligence for security teams.

${report.description || 'No additional description provided.'}

KEY FINDINGS
============

• Increased ${report.category.toLowerCase()} activity detected in multiple regions
• Emerging threat vectors require immediate attention
• Supply chain vulnerabilities identified in critical sectors
• Coordination between threat actors shows sophisticated planning

THREAT ANALYSIS
===============

Overview:
The ${report.category.toLowerCase()} threat landscape has evolved significantly during this reporting period. Our analysis indicates a ${Math.floor(Math.random() * 40 + 10)}% increase in related incidents compared to the previous period.

Impact Assessment:
High-priority targets include financial institutions, government agencies, and critical infrastructure providers.

Geographic Distribution:
Primary activity concentrated in North America and Europe, with emerging hotspots in Asia-Pacific region.

RECOMMENDATIONS
===============

1. Implement enhanced monitoring protocols for identified threat vectors
2. Review and update incident response procedures
3. Conduct threat hunting exercises focused on discovered TTPs
4. Coordinate with industry partners for information sharing
5. Deploy additional security controls in high-risk environments

INDICATORS OF COMPROMISE
========================

IOC-001: Suspicious domain registrations following known patterns
IOC-002: Malicious IP addresses associated with C&C infrastructure
IOC-003: File hashes of known malware variants
IOC-004: Email patterns used in phishing campaigns

TECHNICAL DETAILS
=================

[Technical analysis would be included here in a production report]

APPENDIX
========

For questions about this report, contact: intelligence@premonix.com
Report Classification: ${report.severity.toUpperCase()}
Distribution: Authorized Personnel Only

---
Generated by Premonix Threat Intelligence Platform
© ${new Date().getFullYear()} Premonix. All rights reserved.
    `.trim();
  };

  const downloadReport = async (report: Report, format: 'pdf' | 'txt' = 'txt') => {
    try {
      const success = generateReportPDF(report);
      
      if (success) {
        toast({
          title: "Download Started",
          description: `${report.title} is being downloaded.`,
        });
        return true;
      } else {
        throw new Error("Failed to generate report");
      }
    } catch (error) {
      console.error("Download error:", error);
      toast({
        title: "Download Failed",
        description: "There was an error downloading the report. Please try again.",
        variant: "destructive",
      });
      return false;
    }
  };

  return {
    downloadReport,
  };
};