// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eydehwbjzpanyzzshgyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5ZGVod2JqenBhbnl6enNoZ3lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MTkwNTgsImV4cCI6MjA2NDQ5NTA1OH0.Z10WSK7wpShUcOPXK1Qa8qlITuf_CsMpdQnyNWvFCXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});